[project]
name = "stx-escrow"
description = "Trustless escrow system for Stacks blockchain"
authors = ["serayd61"]
telemetry = false
cache_dir = "./.cache"
requirements = []

[contracts.escrow-core]
path = "contracts/escrow-core.clar"
clarity_version = 2
epoch = 2.5

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

